### ISSUE TITLE
Others languages ?

### ISSUE THREAD

**Issue by bepolymathe** [hkgnp/logseq-datenlp-plugin#1]
Hi, 

Thanks for this plugin . It is very useful! I even think it would be ideal in different languages. Is it in your goals? Or only in English?

**Comment by bepolymathe** [comment]
I understand that it would be a big job. A minimal solution could be to propose that English remains the base, but in that case you would need an option to remove the English word once the parsing is done when writing in another language. 

Example

![image](https://user-images.githubusercontent.com/29939805/150413296-e6f112cb-8d13-4d04-a1cc-e84d6480da36.png)

Become 

![image](https://user-images.githubusercontent.com/29939805/150413354-c4862ca0-e829-42d7-bcea-bd42384a3cba.png)

Where "demain" is "tomorrow" in french.

**Comment by hkgnp** [comment]
Added support for french, dutch and japanese. Can take a look at v1.8.

![demo4](https://user-images.githubusercontent.com/47936793/150470523-7593407d-e2bf-4a73-889d-170f68fbe4f1.gif)
!

**Comment by bepolymathe** [comment]
Thank you for your promptness but I have a problem on my side. I have updated to the new version but I can't get the new language settings to take into account. 

1. I open the plugin settings
2. I put "fr" instead of "en" (default)
3. I save the config file
4. I restart logseq
5. The parameters are back to "en" by default

**Comment by hkgnp** [comment]
Hi!
Apologies, this should be fixed in v1.92 in the marketplace.
Can I check if you are using the plugin from the marketplace or manually?

**Comment by bepolymathe** [comment]
Thanks for the update. I just tried with the version 1.94 but I have the same problem. The only difference is that I have no default language (`" "`) instead of `"en"`.

I install from the marketplace

**Comment by hkgnp** [comment]
Apologies, please try v2.1 from the marketplace.

**Comment by bepolymathe** [comment]
OK, thanks. It works for french recognition but "parse date" insert again an english format (relatif to other issue)

![image](https://user-images.githubusercontent.com/29939805/150632333-7aa9b64a-c045-4fae-80da-92c167bc8eeb.png)

**Comment by hkgnp** [comment]
What does your journal page date look like?

**Comment by bepolymathe** [comment]
You want to say date format ? 

`22-01-2022`

**Comment by hkgnp** [comment]
Could you try the latest v2.5 update and see if the problem persists?

**Comment by bepolymathe** [comment]
I just tried it with this version. I have again the problem of saving the settings. They are not taken into account after restarting logseq...

**Comment by hkgnp** [comment]
Could you copy and paste here what is in your settings file please?

**Comment by hkgnp** [comment]
Refer to: #2 as language issue is resolved.
