### ISSUE TITLE
Unexpected behavior of "@from" after today’s upgrade

### ISSUE THREAD

**Issue by georgd** [hkgnp/logseq-datenlp-plugin#11]
**Edit** I just found out that this is the behaviour on today’s page.

After upgrading to the newest version, blocks with `@from` disappear if entered in today’s journal page 

I can reproduce it with the following block: 

```
[[datenlp]] @from 11 to 12
```

The page `datenlp` is not created and the block’s contents are deleted. In the graph’s git history I can see that the block was cleared without any other page being modified.

**Comment by georgd** [comment]
A second unexpected behavior:  when adding a block with `@from ...` without a date on a journalpage different from today’s, the block ist saved in today’s page instead of the page where it was created on.

Also, relative dates seem generally to be calculated from the current date: adding a block on the page 2025-03-07 with `[[datenlp]] @from 10 to 12 on saturday` will save the block in the page 2022-02-26 when I would expect it on a page in 2025.

**Comment by hkgnp** [comment]
Thanks for surfacing this. I think I have not tested my last commit completely.

Please update again to 3.9.1. I've reverted the changes.

**Comment by georgd** [comment]
Yes, looks as good as before, thanks for the quick fix.

Loooking forward to a new version of the new functionality :)
