### ISSUE TITLE
Time is not being prased

### ISSUE THREAD

**Issue by meldarionqeusse** [hkgnp/logseq-datenlp-plugin#13]
Hi I am new to logseq so I might be doing something wrong but I followed the step you outlined I believe see screenshots below and as you can see time is not being parse just the date.
![image](https://user-images.githubusercontent.com/21668964/156366070-a6470b25-b818-48db-8b7a-5e6ab6114079.png)

![image](https://user-images.githubusercontent.com/21668964/156366103-08e1c287-280c-42e2-a2dc-e319e10c04dd.png)

![image](https://user-images.githubusercontent.com/21668964/156366132-004ff372-af0a-4cad-9dc4-8f75e4ae910a.png)

Similarly with semi and auto parsing
![image](https://user-images.githubusercontent.com/21668964/156366173-63e9ca53-ad1e-4811-a98b-b50f05471b12.png)
![image](https://user-images.githubusercontent.com/21668964/156366194-65980bae-3525-41e8-a358-4d5e9c6d1b17.png)

I am using logseq 0.6.1 on Windows 10.

Thank you for this plugin.

**Comment by meldarionqeusse** [comment]
Ok it parsed as you described but this demo is a bit misleading then cause you do Meet friend on Sunday at 5pm/parse dates

https://github.com/hkgnp/logseq-datenlp-plugin/blob/master/screenshots/demo.gif

**Comment by hkgnp** [comment]
Yes that was an old iteration. Apologies I should be updating the readme!
