### ISSUE TITLE
Adding extra square brackets ]] upon clicking on parse line cause new pages to be created

### ISSUE THREAD

**Issue by meldarionqeusse** [hkgnp/logseq-datenlp-plugin#14]
Steps to replicate the issue

Write date and auto parse it:
![image](https://user-images.githubusercontent.com/21668964/156370182-f96987e5-b79b-46e7-a45d-faa1b0021581.png)
![image](https://user-images.githubusercontent.com/21668964/156370192-c401fbd7-d4d9-4021-80ac-8204924de879.png)

Go back to edit the line and press enter
![image](https://user-images.githubusercontent.com/21668964/156370208-943b1953-b2f2-448f-b6e2-554982a638ba.png)

New ]] inserted automatically at the end
![image](https://user-images.githubusercontent.com/21668964/156370225-88d895c1-2e52-4590-be26-3464c677d17e.png)
if you repeat this it will continue inserting square brackets

**Comment by hkgnp** [comment]
Fixed in v3.9.4.
