### ISSUE TITLE
Adding date on task completion is incorrect with scheduled/deadline/logbook

### ISSUE THREAD

**Issue by scottcs** [hkgnp/logseq-datenlp-plugin#15]
I absolutely love the new functionality of task completion with adding a date reference to the task. There is one thing that is not quite working with it, however.

If I have a task that is already scheduled (using `/schedule`), or has a deadline, or has been in the `DOING` state for a while and has a logbook associated with it, and I use cmd-shift-d to complete the task and add a link to today's date, it adds the link at the end of the entire block rather than at the end of the task description. Logseq does not seem to recognize this task on the journal page, unfortunately.

**Example**:
<img width="205" alt="Screen Shot 2022-03-26 at 5 23 58 PM" src="https://user-images.githubusercontent.com/1170636/160261438-9dd266e2-04c6-47e2-8ca7-a4580d1126c2.png">

**Observed behavior**:
<img width="207" alt="Screen Shot 2022-03-26 at 5 24 07 PM" src="https://user-images.githubusercontent.com/1170636/160261441-ad521cda-92e9-42d8-a96f-319fcd710f2d.png">

**Desired behavior**:
<img width="277" alt="Screen Shot 2022-03-26 at 5 27 34 PM" src="https://user-images.githubusercontent.com/1170636/160261477-016eb4ac-eaf3-4623-a14e-5f0f429092ac.png">

**Comment by hkgnp** [comment]
Fixed in v3.9.9. Pls try and see how it goes.

**Comment by scottcs** [comment]
Working much better for scheduled and deadline `TODO` state, thank you!

I did notice another problem, though. When a task is already in the `DOING` state and I use `cmd-shift-d`, it does not mark the task as `DONE` and also puts the date after the LOGBOOK entry.

**Comment by hkgnp** [comment]
Could you try with 3.9.11 please?
Thanks.

**Comment by scottcs** [comment]
Yes, it is all working now!

The only weird thing is if a task has no scheduled and no deadline, is in the `DOING` state, then hit `cmd-shift-d`, the date reference is added on a new line instead of at the end of the task description. But Logseq still sees it and shows it in linked references on the journal page, so I would say it is working.

Thanks again so much!
