### ISSUE TITLE
Plugin not unregistered when uninstalled and  trying to install again

### ISSUE THREAD

**Issue by danieltomasz** [hkgnp/logseq-datenlp-plugin#17]
when uninstalling  plugin and installing from market place without restarting  logseq I am getting this error

<img width="354" alt="image" src="https://user-images.githubusercontent.com/7980381/163490884-be6a9f26-d5c6-4e1e-9d62-d94482f02532.png">

Not sure if this is logseq error how it handle uninstalled plugins unregistering of  processes or  this plugin specific, this plugin is the first time I am  getting this error

plugin 3.10.2 logseq 0.6.5

**Comment by hkgnp** [comment]
Hi, for plugins with shortcuts, this tends to happen if Logseq is not restarted first.
It is good practice to restart Logseq each time you uninstall a plugin so as to remove these artefacts.
