### ISSUE TITLE
plugin failed to load plugin

### ISSUE THREAD

**Issue by XinLi0111** [hkgnp/logseq-datenlp-plugin#19]
When I open the logseq, the plugin doesn't work at all, if I close and re-open the plugin in logseq, it works again.
logseq version 0.6.9-0.7.0
![image](https://user-images.githubusercontent.com/31495943/170173478-ca56c1ec-bd24-48ad-b50b-aa2af9eb474a.png)

**Comment by hkgnp** [comment]
Sorry could you provide more info? Did you install it from the marketplace? What works, and then what does not work? How do you close and re-open the plugin? What do you mean by it works again?

**Comment by XinLi0111** [comment]
Yes, I installed it from the marketplace, version 3.10.3.

configure of the plugin, semi-prase:
![image](https://user-images.githubusercontent.com/31495943/170175307-c0be2e94-45a4-4190-86d0-1cf5a0b2388b.png)

here is how I do to re-open the plugin:
![image](https://user-images.githubusercontent.com/31495943/170175233-b50a5741-27cc-4544-8812-9ebd9458afb2.png)

when I type "@today" in a block, and then press `esc` key, nothing happened, it was prased as "[[2022-05-25]]",  And when I press `ctrl+shift+p` open the command palette, I can't find any command start with "@" (e.g. @goto prased date). 

If I re-open the plugin as above, all things go well.

**Comment by hkgnp** [comment]
Thanks for sharing. I am not able to replicate your issue, even with the same environment.

Could you try the following, please:
1) Uninstall the plugin.
2) Close Logseq.
3) Go to `.logseq/settings` and delete the logseq-datenlp-plugin.json file.
4) Open Logseq.
5) Install the plugin.
6) Restart Logseq.

**Comment by XinLi0111** [comment]
still not work. but it might be the logseq problem, I also found some plugins failed to be loaded.

**Comment by hkgnp** [comment]
I see, noted with thanks.
Will close this issue here first then.
