### ISSUE TITLE
Generated date is in wrong format

### ISSUE THREAD

**Issue by croogie** [hkgnp/logseq-datenlp-plugin#20]
I have a config in form:
![image](https://user-images.githubusercontent.com/33229/173585572-b16cd3b4-e655-451d-95c0-9d5871d72cd6.png)
but inline dates are generated as 
![image](https://user-images.githubusercontent.com/33229/173587402-15d04cc6-62e4-4467-97b2-3869020a260a.png)
![image](https://user-images.githubusercontent.com/33229/173587424-cee17064-139f-4496-a743-a7586bc6429c.png)

am I doing something wrong?

**Comment by hkgnp** [comment]
Please try again in v3.11.2.

**Comment by 23727** [comment]
I am also experiencing this. 

I find the bug occurs when using '@' to parse the date; however, when parsing for a schedule or deadline with % and ^, the plugin works as expected

**Comment by hkgnp** [comment]
Are you on the latest version?

**Comment by 23727** [comment]
UPDATE: tested it today and it works just as expected—coffee bought :)

**Comment by jacklaing** [comment]
This is happening to me in v3.11.2 for the date format EEE MMM do, yyyy when I do semi-auto parsing with @. I get [[Oct 7th, 2022]] instead of [[Fri Oct 7th, 2022]].

**Comment by hkgnp** [comment]
I don't seem to have "EEE MMM do, yyyy" as an option in Logseq though.

**Comment by natrius** [comment]
It does not seem to work for me as well. I set `E, dd.MM.yyyy` and/or `EEE, dd.MM.yyyy`. Using `tomorrow/parse inline` results in `[[T, 11.10.2022]]`. Problem, my sites are labeled `Mon, 10.10.2022` -> i tried reindexing after setting from E to EEE, but that did not change anything.

**Comment by natrius** [comment]
I did not change anything "in" or "with" this plugin, i changed a logseq setting.

**Comment by natrius** [comment]
But, that does not change the initial problem, doesn't it? I tried with `E, dd.MM.yyyy`, expected `Mon, 10.10.2022` and got `[[T, 11.10.2022]]`. The change happened afterwards to try around, sorry for the confusion.

**Comment by jacklaing** [comment]
> E => T, while EEE => Tuesday

In my experience EEE = Tue, not Tuesday.

**Comment by hkgnp** [comment]
> > I don't seem to have "EEE MMM do, yyyy" as an option in Logseq though.
> 
> I used the config.edn to apply the date format.
> 
> I've tried uninstalling and reinstalling the plugin and I have the same issue.

I've only provided support for date formats in the dropdown list. This is perhaps why it isn't working.

Regarding the issue with E and EEE, what I was trying to say is that while E is supposed to be T, Logseq interprets it as an EEE. Hence, it's more foolproof if one avoids using any date formats with just a singular E in it.
