### ISSUE TITLE
feature request: Date ranges

### ISSUE THREAD

**Issue by gustavoip** [hkgnp/logseq-datenlp-plugin#21]
It would be awesome if we can have date ranges expansion. For example:

Specifying the exactly range:

@2022-02-02_2022-02-10 -> [[Feb 2nd, 2022]], [[Feb 3rd, 2022]], [[Feb 4th, 2022]], [[Feb 5th, 2022]]... [[Feb 10th, 2022]]

OR:

@2022-02-(02, 26) ->  [[Feb 2nd, 2022]], [[Feb 3rd, 2022]], [[Feb 4th, 2022]], [[Feb 5th, 2022]]... [[Feb 28th, 2022]]
@2022-02-(02, -5) -> - [[Feb 1st, 2022]], [[Jan 31st, 2022]], [[Jan 30th, 2022]], [[Jan 29th, 2022]], [[Jan 28th, 2022]]

**Comment by hkgnp** [comment]
Could you share more on the use case please?

**Comment by gustavoip** [comment]
For example, let's suppose I have a sprint that will happen from  [[Feb 2nd, 2022]] until [[Feb 16th, 2022]]. So I can define somewhere that sprint will occur in those days.

`
Sprint to do X: [[Feb 2nd, 2022]], [[Feb 3rd, 2022]], [[Feb 4th, 2022]], [[Feb 5th, 2022]]... [[Feb 10th, 2022]]
`

In the following days, when I look into my daily journal,  I will see a reference for that sprint. That would help me to manage those kinds of events.

**Comment by hkgnp** [comment]
I see. You may want to look at using another plugin: https://github.com/hkgnp/logseq-recurrence-plugin.
