### ISSUE TITLE
Notification feature for timed blocks

### ISSUE THREAD

**Issue by emms007** [hkgnp/logseq-datenlp-plugin#22]
It would be great if the plugin could initiate a notification popup upon a time-defined schedule or deadline is reached.
For instance, I'd type
`- TODO remember to call my mom %today 3pm`

And by 3pm I would have a notification popup to remind it to me if still TODO. Notification would be a screen pop-up with a sound visualization. It seems this is managed by https://www.electronjs.org/docs/latest/tutorial/notifications at best, or at minimum a start with logseq.ui.ShowMsg.

Ideally, I could either: [snooze the notification], [jump to the original block], or [simply close it].

**Comment by hkgnp** [comment]
Please see https://twitter.com/hkgnp/status/1589526398439673857. It's available in the latest version.
Unfortunately, there are some limitations for the Electron Notifications API hence only the snooze function is available if you click on the notification.
