### ISSUE TITLE
[Feature Request]: set config to disable or change default hotkeys

### ISSUE THREAD

**Issue by alanbobs999** [hkgnp/logseq-datenlp-plugin#25]
`a p` `s p` or any other datenlp-plugin hotkeys may conflict with my existing shortcuts settings, so can there provide any way to disable or change these hotkeys?  Thank you.

**Comment by hkgnp** [comment]
You're right. Ever since the function to toggle auto and semi-auto parsing existed in the plugin settings, this set of hotkeys are redundant. Have since deprecated it in the new version.
