### ISSUE TITLE
Slash commands broken since 3.12.2

### ISSUE THREAD

**Issue by knoopx** [hkgnp/logseq-datenlp-plugin#26]
they all fail to parse and replace, an error is thrown (looks like a null object ref when accessing chronos?)

```
ncaught (in promise) TypeError: Cannot read properties of undefined (reading 'en')
    at b (index.64944076.js:1:382543)
```

**Comment by hkgnp** [comment]
What slash command are you referring to?

**Comment by hkgnp** [comment]
Please update to latest version and try again.

**Comment by knoopx** [comment]
Fixed 👍🏻
