### ISSUE TITLE
feature request on reminders

### ISSUE THREAD

**Issue by kumaresh0** [hkgnp/logseq-datenlp-plugin#27]
- [ ] Show reminder with the task name
- [ ] Clicking reminder should take it the task block
- [ ]  Ignoring reminder should auto snooze for given time 
I think this may be great for the reminder option

**Comment by hkgnp** [comment]
There is a better reminder plugin out there in the Logseq marketplace: https://github.com/sethyuan/logseq-plugin-reminder
