### ISSUE TITLE
"@wednesday" doesn't work only v3.13.3

### ISSUE THREAD

**Issue by YU000jp** [hkgnp/logseq-datenlp-plugin#29]
Worked in v3.13.2 but not in v3.13.3
https://github.com/hkgnp/logseq-datenlp-plugin/commit/e7a5f6ac2bc44fa727fc7637a7edf36b82284dcd#diff-91633b06e7ff7dd238d9a23e87b3d1a7ab0db34b473da37465e5354c579367d6

**Comment by hkgnp** [comment]
What do you mean by `@wednesday`?
It's still parsing for me though.

**Comment by YU000jp** [comment]
Sorry, could you try "Semi-auto Inline Parsing" in v3.13.3.  doesn't work.

**Comment by hkgnp** [comment]
Hmm, just tried it and it does. I typed ***@***.***` and it parses to
16-11-2022.

**Comment by YU000jp** [comment]
It worked after uninstalling other plugins.
It seems that Logseq did not work properly due to a conflict with another plugin. It hasn't worked for several days. I searched by elimination method, but I don't know which one was the cause.
