### ISSUE TITLE
Processed dates use different format from Logseq default.

### ISSUE THREAD

**Issue by rosslaird** [hkgnp/logseq-datenlp-plugin#3]
Scheduled date via regular LogSeq `/Scheduled` method:
`SCHEDULED: <2022-01-21 Fri>`
Scheduled date shown by plugin with `/parse scheduled`:
`SCHEDULED: <2022-21-1 Friday>`
I have made no changes to my date format since I started using Logseq. So, it's the default: `MMM do, yyyy`
Version 1.8 of the plugin and latest LogSeq beta 0.5.9.

_Originally posted by @rosslaird in https://github.com/hkgnp/logseq-datenlp-plugin/issues/2#issuecomment-1018203195_

**Comment by hkgnp** [comment]
Thanks for the report!

Please try v1.9 to see if it's ok. Thanks!

**Comment by rosslaird** [comment]
Thanks for your quick reply (as usual!). I updated the plugin, restarted Logseq, and the date formats are now consistent. That's great. (I am also still seeing what I reported in issue #4.)

**Comment by rosslaird** [comment]
Sorry, I spoke too soon. There is something funky going on with dates in Logseq as well. After restarting, I'm now seeing scheduled dates created like this:

`SCHEDULED: <[[Jan 21st, 2022]] Fri>`

That is different from what I was seeing earlier. it is also different from what the plugin creates. (I have not changed anything in Logseq.) Not sure what's going on here.

**Comment by hkgnp** [comment]
Oh this is indeed very strange. Plugins definitely do not have the permissions to make changes to the system.
Can I check if you are manually installing the plugin or via the marketplace?
I've to go off for a meeting soon so may not be able to respond. But if you are installing it manually, you may want to try the marketplace version first, but do follow the steps below:

1. Uninstall the plugin.
2. Close Logseq
3. Go to `.logseq/settings` and delete `logseq-datenlp-plugin.json`
4. Open Logseq
5. Go to marketplace to install the plugin
6. Restart Logseq

**Comment by rosslaird** [comment]
I installed the plugin from the marketplace. And, when I disable the plugin, Logseq reverts to the `Scheduled` format I was seeing previously today (the format that seems correct) and the click-away problem of issue #4 disappears.

**Comment by hkgnp** [comment]
Oh I think what the library is using is seeing a date and automatically converting it to your user preferred format. I need to get it to ignore whatever is in SCHEDULED. Will update when this has been fixed.

**Comment by rosslaird** [comment]
Seems to be working now: showing dates consistent with what Logseq's `/Scheduled` method shows, and not jumping in and out with conflicting dates. Excellent. Thanks for your work on this and for the many contributions you make to the Logseq community.
