### ISSUE TITLE
Plugin not capturing anymore some simple string

### ISSUE THREAD

**Issue by emms007** [hkgnp/logseq-datenlp-plugin#30]
Hello Hkgnp,

I see today that some nlp basic scheduling is not working anymore.
I am pretty sure this worked in the past. Any reason you'd see for regression or it never worked?
`Remember to bring milk %in 3 days`

I checked my language, and will set to "en"
Thanks

**Comment by hkgnp** [comment]
Hmm, honestly I don't think it was "in 3 days". Try "3 days later".

**Comment by emms007** [comment]
"3 days later" works... I must have been dreaming :)
Thanks  👍  :D

**Comment by emms007** [comment]
Are you sure nothing changed on the analysis?
I have another case I just typed and did not work : "order milk %in a month"
That's a lot of things that are not working that seems naturel to my usages since months.

**Comment by emms007** [comment]
BTW https://sherlock.neil.gg/ can translate the ones I have in mind (in 3 days, in a month)

**Comment by hkgnp** [comment]
The plugin has not used Sherlock for a few versions already.

Could you try `Order milk in %a month`.
