### ISSUE TITLE
Adding a date to the end of a block with a logbook removes a newline, breaking the logbook

### ISSUE THREAD

**Issue by phoenixeliot** [hkgnp/logseq-datenlp-plugin#31]
1. Type in a block
2. Toggle it to NOW
3. Leave the block
4. Move back into it, toggle it to DONE. This creates a logbook entry.
5. Then type an @-date like `@nov 11` at the end of the block
6. Press down to leave the block
7. The result is that it will consume the newline at the end of the block, merging the block with its logbook text, and duplicating the logbook text

https://user-images.githubusercontent.com/491376/206965688-962ac714-0738-4def-998a-bae3e97599fd.mov

This does not happen if there is text after the date, or if you use @today.

**Comment by phoenixeliot** [comment]
I think this needs these settings, which I don't know if they're non-default or not
```
 ;; logbook setup
 :logbook/settings
 {
 ;; :with-second-support? false ;limit logbook to minutes, seconds will be eliminated
 :enabled-in-all-blocks true ;display logbook in all blocks after timetracking
 ;; :enabled-in-timestamped-blocks false ;don't display logbook at all
 }
 ```

**Comment by hkgnp** [comment]
Please try with v3.13.4.
