### ISSUE TITLE
Different behavior if the block is a todo (it's incorrectly parsing)

### ISSUE THREAD

**Issue by amrmjd** [hkgnp/logseq-datenlp-plugin#32]
Works correctly if it's a standard block but if the block is a todo and I write "tomorrow" and then "/parse dates" it sets the date as today:
![2023 02 15-01 59 57PM@2x](https://user-images.githubusercontent.com/3620335/219126960-d9bc4e50-ed75-4c72-928c-a9495650b625.png)

**Comment by hkgnp** [comment]
Sorry I cannot reproduce this issue. Works on mine. Can you show what your
block looks like before it gets parsed?
