### ISSUE TITLE
Parsing multiple tokens in one block

### ISSUE THREAD

**Issue by Zachu** [hkgnp/logseq-datenlp-plugin#36]
Hey!

I noticed that the plugin fails to parse multiple dates in one block. With following block and Semi-auto Parsing enabled only the first `@yesterday` token gets expanded correctly when exiting the block. Revisiting and exiting the block again does resolve the second `@today` token.

```md
- @yesteday and @today
```

After one visit:
```md
- [[2023-03-05]] and @today
```

After second visit:
```md
- [[2023-03-05]] and [[2023-03-06]]
```

Would be great to have them all parsed at one go =)

**Comment by hkgnp** [comment]
Feature available in: [v4.2.0](https://github.com/hkgnp/logseq-datenlp-plugin/releases/tag/v4.2.0)
