### ISSUE TITLE
typed times erased when @date is parsed

### ISSUE THREAD

**Issue by Holanda73** [hkgnp/logseq-datenlp-plugin#39]
hi,
Issue, sometimes a @date is parsed but the time is erased after enter

I use the plugin in language NL.

Example issue:
I type:  meeting planned @morgen om 11.30 uur
I hit enter
result is that it now says:
meeting planned [[25-05-2023]]

Comment: the " om 11.30 uur" has been erased automatically.

To avoid this issue, I type the date, then hit enter and then go back to add the hours.

**Comment by hkgnp** [comment]
Fixed in [v4.0.4](https://github.com/hkgnp/logseq-datenlp-plugin/releases/tag/v4.0.4)
