### ISSUE TITLE
Processed date is correct until bullet is no longer active

### ISSUE THREAD

**Issue by rosslaird** [hkgnp/logseq-datenlp-plugin#4]
With version 1.8 of the plugin and Logseq 0.5.9, the processed date for a scheduled or deadline item shows as intended until I click away, then a different date is shown. For example, this is the result when I create a bullet and use the plugin to insert a scheduled item using  `tomorrow /parse scheduled`:

`Item that I want to schedule for [[Jan 21st, 2022]]
SCHEDULED: <2022-21-1 Friday>`

This is what I see when a click away from that bullet:

`Item that I want to schedule for [[Jan 21st, 2022]]
SCHEDULED: <2023-09-1 Friday>`

Note that the scheduled date now shows September 1, 2023. If I click back into the bullet, the date changes to the intended date again (tomorrow); if I click away, it reverts to 2023 on the scheduled line. This only happens with scheduled or deadline items; `parse dates` works as intended.

**Comment by hkgnp** [comment]
Yeah this is the issue that TokyoMike was experiencing. Could you try to update to v1.9?

**Comment by rosslaird** [comment]
Still showing in 1.9.

**Comment by hkgnp** [comment]
Please see the instructions in https://github.com/hkgnp/logseq-datenlp-plugin/issues/3#issuecomment-1018225108 and see if the problem persists?

**Comment by rosslaird** [comment]
Seems to be working properly now. Because I had installed the plugin from the marketplace, and the instructions say that they are for when "you are installing it manually," I thought they didn't apply to my situation. But they do, and they worked. Thanks again.
