### ISSUE TITLE
Allow Config to choose Special Char in Semi Parsing.

### ISSUE THREAD

**Issue by amanhigh** [hkgnp/logseq-datenlp-plugin#40]
Hi,
I mostly use schedule rather than direct date or Deadline. Hence i would want to use `@` for Scheduled and `%` can go for dates. 

If Plugin can make this configurable it would be great help as i would change `@` for Schedule which i use the most and is easy to type.
Hopefully this would be small change in plugin setting.

Thanks for the Great Plugin.

**Comment by amanhigh** [comment]
Thanks for the change but i tried version 4.2.0. Some how i am unable to get date parsing Worknig.

Strings Tried
* ^sun
* ^10d
* January
* jan

I Tried these with @ and % also but not working. I restarted Logseq and did reloads as well.

My Settings

```
{
  "auto": false,
  "semiAuto": true,
  "lang": "",
  "notifications": false,
  "defaultSnooze": 5,
  "useBlockAsAlarmTitle": true,
  "disabled": false,
  "preferredDateFormat": "MMM do, yyyy"
}
```

**Comment by hkgnp** [comment]
Can you share screenshots of what you mean by it is not working?

**Comment by amanhigh** [comment]
Settings and Plugin Versions
![Screenshot__20230916__114947](https://github.com/hkgnp/logseq-datenlp-plugin/assets/409973/d3d59bdf-62d0-431e-bdb9-7b76fab1093c)
![Screenshot__20230916__115008](https://github.com/hkgnp/logseq-datenlp-plugin/assets/409973/dbb844a2-cdd0-476d-a600-b3da6d36a27f)
![Screenshot__20230916__115040](https://github.com/hkgnp/logseq-datenlp-plugin/assets/409973/084267c5-5b6d-4b55-913c-4498cf256dcd)

Testing this Plugin which is not expanding Dates. Tried Reload and Restart Multiple Times.
![Screenshot__20230916__115120](https://github.com/hkgnp/logseq-datenlp-plugin/assets/409973/4d9d13a3-3674-4522-aa5c-fd7376c278e3)

**Comment by hkgnp** [comment]
I'm sorry I am not able to reproduce your problem. I've configured my settings to be exactly the same as yours and it works fine. I am not sure if you may have other plugins interfering though. It is a possibility.

**Comment by amanhigh** [comment]
Thanks for your efforts. Plugin interference could be possible, would try it out on fresh installation with other plugins disable and report.

**Comment by hkgnp** [comment]
Feel free to re-open this ticket after your test.
