### ISSUE TITLE
Elements in code blocks and inline code should not parsed

### ISSUE THREAD

**Issue by paranoid-bunny** [hkgnp/logseq-datenlp-plugin#41]
The plugin picks up dates from inside code blocks and inline code, and some code can easily contain text that looks like a date to the plugin; for example
````markdown
```go
fmt.Printf("%03d\n", rnt1)
```
````
will create a scheduled block set to 3 days in the future and will remove the `%03d` from the block when semi-auto parsing is enabled. 

I don't think wanting to parse dates from within code blocks is common and I would not even expect the plugin to anyways, even when using slash commands - so perhaps inline code/code blocks should be ignored completely both when using slash commands and (semi-)auto parsing?

**Comment by hkgnp** [comment]
Resolved in https://github.com/hkgnp/logseq-datenlp-plugin/releases/tag/v4.0.2
