### ISSUE TITLE
Past "week"s not handled

### ISSUE THREAD

**Issue by chadkennedyonline** [hkgnp/logseq-datenlp-plugin#42]
7 days ago - Works
1 week from now - Works
1 week ago - Does not work

![image](https://github.com/hkgnp/logseq-datenlp-plugin/assets/13368197/4dec4473-be07-4071-8f5e-cead7c106a1e)

I tested all 3 on https://sherlock.neil.gg/ and they all work there.

**Comment by hkgnp** [comment]
Fixed in [v4.0.3](https://github.com/hkgnp/logseq-datenlp-plugin/releases/tag/v4.0.3)
