### ISSUE TITLE
Feature Request: Inline date parsing

### ISSUE THREAD

**Issue by ahpatel** [hkgnp/logseq-datenlp-plugin#43]
Would it be possible to add an option to parse dates _inline_?

For example, I type the following bullet
`- TODO this task needs to be completed by July 31st.`

When I `/parse date` it adds a date attribute under the bullet.
`- TODO this task needs to be completed by July 31st.`
`date:: [[Jul 31, 2023]]`

What I'd like for it to do instead is replace the date inline so the bullet reads:
`- TODO this task needs to be completed by [[Jul 31, 2023]]`

**Comment by hkgnp** [comment]
You can preface it by typing something like "TODO this task needs to be completed by @July 31st"
________________________________
From: Anish Patel ***@***.***>
Sent: Thursday, July 13, 2023 1:37 PM
To: hkgnp/logseq-datenlp-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hkgnp/logseq-datenlp-plugin] Feature Request: Inline date parsing (Issue #43)


Would it be possible to add an option to parse dates inline?

For example, I type the following bullet
- TODO this task needs to be completed by July 31st.

When I /parse date it adds a date attribute under the bullet.
- TODO this task needs to be completed by July 31st.
date:: [[Jul 31, 2023]]

What I'd like for it to do instead is replace the date inline so the bullet reads:
- TODO this task needs to be completed by [[Jul 31, 2023]]
