### ISSUE TITLE
Preferred date format in config file is not used

### ISSUE THREAD

**Issue by LawsonJohnson** [hkgnp/logseq-datenlp-plugin#44]
Below is my config.json for the plugin (the date format is also set the same way in my config.edn file).
```
{
  "auto": false,
  "semiAuto": true,
  "lang": "",
  "notifications": false,
  "defaultSnooze": 5,
  "useBlockAsAlarmTitle": true,
  "disabled": false,
  "preferredDateFormat": "EEEE, MMMM do, yyyy"
}
```

Per this setting, I would expect the dates created by the plugin would follow this format:

`[[Wednesday, July 19th, 2023]]` but instead they are generated as `[[Jul 19th, 2023]]`.

**Comment by hkgnp** [comment]
Currently the only date formats supported are those that are selectable in Logseq.

There isn’t support for custom dates yet.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Lawson Johnson ***@***.***>
Sent: Thursday, July 20, 2023 12:02:47 AM
To: hkgnp/logseq-datenlp-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hkgnp/logseq-datenlp-plugin] Preferred date format in config file is not used (Issue #44)


Below is my config.json for the plugin (the date format is also set the same way in my config.edn file).

{
  "auto": false,
  "semiAuto": true,
  "lang": "",
  "notifications": false,
  "defaultSnooze": 5,
  "useBlockAsAlarmTitle": true,
  "disabled": false,
  "preferredDateFormat": "EEEE, MMMM do, yyyy"
}


Per this setting, I would expect the dates created by the plugin would follow this format:

[[Wednesday, July 19th, 2023]] but instead they are generated as [[Jul 19th, 2023]].

**Comment by hkgnp** [comment]
Just an update: will be adding this feature by the end of the week.
