### ISSUE TITLE
快捷键好像不起作用

### ISSUE THREAD

**Issue by yoghurtdewdew** [hkgnp/logseq-datenlp-plugin#45]
简介里说`a p`和`s p`分别是打开自动和半自动解析日期时间，但我试了下，没有成功打开/关闭的notification，快捷键-plugins里也没有看到有相应的设置

所以如果想用这个快捷键的话应该如何设置呢，我觉得这个快捷键真的很不错会方便很多

<img width="244" alt="image" src="https://github.com/hkgnp/logseq-datenlp-plugin/assets/63794438/e33c6aa4-6a46-43f7-9994-a93dd76fa770">

**Comment by hkgnp** [comment]
This feature has been deprecated in the latest version. Only semi-auto parsing is available.
