### ISSUE TITLE
Not parsing dates "semi-automatically"

### ISSUE THREAD

**Issue by meain** [hkgnp/logseq-datenlp-plugin#46]
```
dex-d4cc9a0b.js:58 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parse')
    at Ga (index-d4cc9a0b.js:58:1310)
    at MutationObserver.IO (index-d4cc9a0b.js:62:333)
```

Probably coming from nothing being available here:
https://github.com/hkgnp/logseq-datenlp-plugin/blob/4a57082d622234e757db709040b6e079ac85749d/src/features/parse/index.ts#L93

I had never updated this setting. Changing the language to something else and changing back to the default (`en`) seems to fix the issue for me.

**Comment by hkgnp** [comment]
Sorry I am to able to reproduce this. Is it still happening?

**Comment by meain** [comment]
After updating to the newer version, I now get a different error:

```
RangeError: Format string contains an unescaped latin alphabet character `n`
 ```

**Comment by hkgnp** [comment]
Looks like a [library issue](https://github.com/date-fns/date-fns/issues/1857).

Is it still parsing even with the error? I am still not able to reproduce it, i.e. I can parse without receiving any errors in developer tools.

**Comment by meain** [comment]
> Is it still parsing even with the error?

Nope, nothing seems to happen.

> Looks like a https://github.com/date-fns/date-fns/issues/1857.

Yup, I tried debugging it and it looks like it is coming from `format` [here](https://github.com/hkgnp/logseq-dateutils/blob/9181e21d6243e779e3d2199898b54bf62569e481/src/index.ts#L4).

**Comment by meain** [comment]
I installed an updated, today. I am only having this issue after the update, but I can't seem to pin it to any particular commit. With the previous version (the one on the day I reported this bug), I was able to get it to work once I had reset the language.)

**Comment by Holanda73** [comment]
I cannot get it to work at all since some recent version.

v4.2.5
I have the language on nl. However I also tried in English and no luck either.

Normally typing ``@vandaag`` gave the me today's date in ``[[16-10-2023]]``.
Now nothing happens. I added a screenshot some examples:
![Scherm­afbeelding 2023-10-16 om 07 41 43](https://github.com/hkgnp/logseq-datenlp-plugin/assets/125112446/00e1074e-2d10-4503-b8f7-0e05e55c0541)

Here are my settings:
![Scherm­afbeelding 2023-10-16 om 07 41 43](https://github.com/hkgnp/logseq-datenlp-plugin/assets/125112446/aeb5b19e-8fda-48ab-bfa1-bb3d3e6db421)

**Comment by meain** [comment]
Huh, I do get the same error with language `nl` and `@vandaag`.

**Comment by Holanda73** [comment]
I wonder what I can check to figure it out?

**Comment by Holanda73** [comment]
> I wonder what I can check to figure it out?

Also checked this:
```
{
  "semiAuto": true,
  "insertDateProperty": false,
  "lang": "nl",
  "specialCharHeading": "",
  "dateChar": "@",
  "scheduledChar": "%",
  "deadlineChar": "^",
  "disabled": false
}
```

**Comment by meain** [comment]
Huh, that is interesting. Looks like using `%` and `^` works, but not `@`.

**Comment by meain** [comment]
@Holanda73 As for `%` not showing anything, you need to have some content in that block for logseq to show the scheduled date.

**Comment by Holanda73** [comment]
> @Holanda73 As for `%` not showing anything, you need to have some content in that block for logseq to show the scheduled date.

agree, sorry you are right, I just tested it. But indeed `` @ `` does not work.
I even removed the plugin and re-installed it (in an earlier version) and it did not help.

**Comment by hkgnp** [comment]
Hi @Holanda73 and @meain, can you share what languages you all are using? 

I suspect what is happening is how the date formats are being returned on your respective computers and `date-fns` expects UTF-8 formats. Would like to confirm this.

**Comment by meain** [comment]
I have English both in my system and specified in the plugin settings(`en`).

**Comment by Holanda73** [comment]
Language set is NL but see my language and regional settings
<img width="503" alt="image" src="https://github.com/hkgnp/logseq-datenlp-plugin/assets/125112446/960c1df3-7746-4d79-950d-a3c9761bc6d7">

**Comment by hkgnp** [comment]
Sorry for the delayed response. Could you try to see if [v4.3.1](https://github.com/hkgnp/logseq-datenlp-plugin/releases/tag/v4.3.1) fixes the issue?

**Comment by Holanda73** [comment]
> Sorry for the delayed response. Could you try to see if [v4.3.1](https://github.com/hkgnp/logseq-datenlp-plugin/releases/tag/v4.3.1) fixes the issue?

Seems it only works if the date text is the only text:
<img width="554" alt="image" src="https://github.com/hkgnp/logseq-datenlp-plugin/assets/125112446/682ad256-f43b-46e0-a4a6-f44fb45a5439">

**Comment by hkgnp** [comment]
Hmm, I still cannot reproduce it.

https://github.com/hkgnp/logseq-datenlp-plugin/assets/47936793/a7f0dee9-6514-430d-86a0-2bda0a99ae54

**Comment by Holanda73** [comment]
> Hmm, I still cannot reproduce it.
> 
>  vandaag.mov 
> 
> Maybe you can try uninstalling the plugin, close Logseq, delete `logseq-datenlp-plugin_layouts.json` and `logseq-datenlp-plugin.json` from `.logseq/settings`, open Logseq, and re-install the plugin?

I closed Logseq and restarted again
now it seems to work. In some weird case a time stamp appeared, but can't reproduce.
So it seems to have been fixed now.

Appreciate the follow up !!!!

**Comment by praveenperera** [comment]
I had the same issue, what fixed it for me.

Uninstall -> Restart LogSeq -> Install

**Comment by meain** [comment]
Same here, looks like it is all good now. Lemme close the ticket! Thank again for the plugin :D
