### ISSUE TITLE
[bug report] Contains unnecessary double-byte character spaces

### ISSUE THREAD

**Issue by YU000jp** [hkgnp/logseq-datenlp-plugin#47]
https://github.com/hkgnp/logseq-datenlp-plugin/blob/4a57082d622234e757db709040b6e079ac85749d/src/features/parse/semi-auto.ts#L55
https://github.com/hkgnp/logseq-datenlp-plugin/blob/4a57082d622234e757db709040b6e079ac85749d/src/features/parse/semi-auto.ts#L58
![image](https://github.com/hkgnp/logseq-datenlp-plugin/assets/111847207/e306474c-6f3f-4e95-88e1-124e7dc0c73a)
(From: https://discuss.logseq.com/t/natural-language-dates/1516/6?u=yu000jp)

**Comment by hkgnp** [comment]
Fixed in latest version.

@YU000jp thanks for the PR. Sorry I saw it after I made the changes.
