### ISSUE TITLE
Parsing scheduled or deadline adds time

### ISSUE THREAD

**Issue by ingepettersen** [hkgnp/logseq-datenlp-plugin#49]
Using semi-auto parsing of scheduled or deadline dates, the current time is also added to the result. This should at a minimum be configurable. I have no use for the time-property being added to my tasks in this way. It only contributes to clutter.

**Comment by hkgnp** [comment]
Update to v4.3.0 and toggle the `removeTime` option in settings.

**Comment by ingepettersen** [comment]
> Update to v4.3.0 and toggle the `removeTime` option in settings.

That did the trick! Thanks 🙌💯
