### ISSUE TITLE
Semi parsing, decoding in the past

### ISSUE THREAD

**Issue by emms007** [hkgnp/logseq-datenlp-plugin#5]
Hello Hkgnp,

I found something you would not expected when semi-parsing this line.
=> "perform something @15sept"

Result is "15 September", but for year 2021 instead of future.
I am puzzled because other dates work fine, such as "@5July" fits well in 2022.

**Comment by hkgnp** [comment]
@emms007 Hi, this isn't a bug per se as it's part of the library. It calls for the nearest year, e.g. 15 Sep 2021 is nearer to today compared to 15 Sep 2022 by 1 day.

**Comment by emms007** [comment]
That makes sense from the library point of view: remaining as generic as possible. 

In the way that I use Logseq/playing with date is definitely closer to a "Todoist"/GetThingsDone/Planning style app. I tried in in Todoist the typing a long-fetch date: it definitely get it in the future. 

I guess the parent library you are using does not have working parameter to nuance this behavior ?

**Comment by hkgnp** [comment]
Yes unfortunately it doesn't. But let me see if there is a workaround.

**Comment by hkgnp** [comment]
@emms007 Hi, I've implemented a fix for this. Do have a go and see if it works in v3.6.

**Comment by emms007** [comment]
Fixed confirmed!
I add another problem related to issue 6 : https://github.com/hkgnp/logseq-datenlp-plugin/issues/6 - I have added a comment, double a typo your logic, not sure if is related to your latest change or note.

Btw v3.6 was not in the market place, I had to install manually

**Comment by hkgnp** [comment]
Will close the issue now. I've replied to the other issue and reopened it.
Strange! I have 3.6 in the marketplace!
