### ISSUE TITLE
Unusual behaviour

### ISSUE THREAD

**Issue by nickriches** [hkgnp/logseq-datenlp-plugin#50]
Hi. I normally use this plugin by choosing PARSE SCHEDULE / PARSE DEADLINE from the dropdown menu. Recently, this has not been working. I select this once and nothing happens. I select it again, and I get "SCHEDULED: <SCHEDULED: <2023-11-09 Thu 17:18>>"

**Comment by hkgnp** [comment]
Sorry, this should be fixed in 4.3.4.
