### ISSUE TITLE
Multiple bugs related to Special Characters

### ISSUE THREAD

**Issue by Zachu** [hkgnp/logseq-datenlp-plugin#51]
I'm sorry but this report is going to have few different bugs cause I see them all kinda relating to each other.

1.) Setting special char to "NA" literally sets it to "NA". I believe it's supposed to "unset" it, right?

So I've set "Character for Scheduled" to be "NA"

`.logseq/settings/logseq-datenlp-plugin.json`
```js
{
  "semiAuto": true,
  "insertDateProperty": false,
  "lang": "en",
  "removeTime": true,
  "specialCharHeading": "",
  "dateChar": "@",
  "scheduledChar": "NA",
  "deadlineChar": "^",
  "disabled": false,
  "auto": false,
  "notifications": false,
  "defaultSnooze": 5,
  "useBlockAsAlarmTitle": true,
  "preferredDateFormat": "yyyy-MM-dd"
}
```

It becomes apparent especially in this example case:

```md
- ## This is some block
  date:: [[2023-10-31]]
  tags:: [[AWS/NAT Gateway]]
```

Exiting that block will change it to:
```md
- ## This is some block
  date:: [[2023-10-31]]
  tags:: [[AWS/NAT Gateway]]
  SCHEDULED: <2023-10-31 Tue>
```

2.) Scheduled blocks are rescheduled many times

At least now with these settings revisiting this block makes it to be:
```md
- ## This is some block
  date:: [[2023-10-31]]
  tags:: [[AWS/NAT Gateway]]
  SCHEDULED: <2023-10-31 Tue>
  SCHEDULED: <2023-10-31 Tue>
  SCHEDULED: <2023-10-31 Tue>
  SCHEDULED: <2023-10-31 Tue>
```

And revisiting it again changes it to:
```m
- ## This is some block
  date:: [[2023-10-31]]
  tags:: [[AWS/NAT Gateway]]
  SCHEDULED: <2023-10-31 Tue>
  SCHEDULED: <2023-10-31 Tue>
  SCHEDULED: <2023-10-31 Tue>
  SCHEDULED: <2023-10-31 Tue>
  SCHEDULED: <2023-10-31 Tue>
  SCHEDULED: <2023-10-31 Tue>
  SCHEDULED: <2023-10-31 Tue>
  SCHEDULED: <2023-10-31 Tue>
  SCHEDULED: <2023-10-31 Tue>
  SCHEDULED: <2023-10-31 Tue>
  SCHEDULED: <2023-10-31 Tue>
  SCHEDULED: <2023-10-31 Tue>
  SCHEDULED: <2023-10-31 Tue>
```

... and so on always increasing exponentially :sweat_smile: 

The same thing can be seen by the default `%` character with following block:

```md
- ## This is some block % foo
  date:: [[2023-10-31]]
```

3.) Disabling both Scheduled and Deadline is "overlapping inline parsing characters".

So setting both to "NA" (which I still assume should be disabled) makes the plugin error with the following message:
> There are overlapping characters for the inline parsing character. Please re-check your settings

Then the plugin sets the settings back to default:
`.logseq/settings/logseq-datenlp-plugin.json`
```json
{
  "semiAuto": true,
  "insertDateProperty": false,
  "lang": "en",
  "removeTime": true,
  "specialCharHeading": "",
  "dateChar": "@",
  "scheduledChar": "%",
  "deadlineChar": "^",
  "disabled": false,
  "auto": false,
  "notifications": false,
  "defaultSnooze": 5,
  "useBlockAsAlarmTitle": true,
  "preferredDateFormat": "yyyy-MM-dd"
}
```

**Comment by Zachu** [comment]
I don't use DEADLINE and SCHEDULED at all and would like to disable parsing of those. Especially when the `%` character makes editing templates a bit hard since I have for example `<% today %>` there sometimes :)

**Comment by e-zz** [comment]
> I don't use DEADLINE and SCHEDULED at all and would like to disable parsing of those. Especially when the `%` character makes editing templates a bit hard since I have for example `<% today %>` there sometimes :)
> 
> Edit:
> 
> As a workaround for now I set up the characters for scheduled and deadline to be something I have no reason ever to type :D This is something that can't be done from the UI though but can be changed from the settins file.
> 
> `.logseq/settings/logseq-datenlp-plugin.json`
> 
> ```json
> {
>   "semiAuto": true,
>   "insertDateProperty": false,
>   "lang": "en",
>   "removeTime": true,
>   "specialCharHeading": "",
>   "dateChar": "@",
>   "scheduledChar": "ə",
>   "deadlineChar": "ð",
>   "disabled": false,
>   "auto": false,
>   "notifications": false,
>   "defaultSnooze": 5,
>   "useBlockAsAlarmTitle": true,
>   "preferredDateFormat": "yyyy-MM-dd"
> }
> ```

Thanks for the info. Also, it's possible to use two characters to better avoid false matches.

``` json
   "dateChar": "@",
   "scheduledChar": ":^",
   "deadlineChar": ":%",
```

**Comment by yoghurtdewdew** [comment]
Hi, will escape the character in `code` ?

**Comment by yoghurtdewdew** [comment]
> Hi, will escape the character in `code` ? I wish to! But I found it didn't.

<img width="396" alt="image" src="https://github.com/hkgnp/logseq-datenlp-plugin/assets/63794438/dd88bd43-6f51-413f-a1b3-c17f662fb562">
<img width="412" alt="image" src="https://github.com/hkgnp/logseq-datenlp-plugin/assets/63794438/e44b59a7-652b-49a1-a50b-096e9420badb">

@hkgnp

**Comment by hkgnp** [comment]
> > Hi, will escape the character in `code` ? I wish to! But I found it didn't.
> 
> <img alt="image" width="396" src="https://private-user-images.githubusercontent.com/63794438/294937960-dd88bd43-6f51-413f-a1b3-c17f662fb562.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3Njk3MDQsIm5iZiI6MTcwNDc2OTQwNCwicGF0aCI6Ii82Mzc5NDQzOC8yOTQ5Mzc5NjAtZGQ4OGJkNDMtNmY1MS00MTNmLWExYjMtYzE3ZjY2MmZiNTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAzMDMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMmIxODk2OWY1ZGM1MWQ5ZjMyMWIxYzU1NjA4NGU2YTczMDk2MDc3OGM3NDU1MDhiMmQ3ODAyYTVjZWJhNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NYL4IwBhRFFWRigLcIQi3OVJdarLpVU7muiX82lUVKE"> <img alt="image" width="412" src="https://private-user-images.githubusercontent.com/63794438/294938046-e44b59a7-652b-49a1-a50b-096e9420badb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3Njk3MDQsIm5iZiI6MTcwNDc2OTQwNCwicGF0aCI6Ii82Mzc5NDQzOC8yOTQ5MzgwNDYtZTQ0YjU5YTctNjUyYi00OWExLWE1MGItMDk2ZTk0MjBiYWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAzMDMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExM2M4Yjc1NDY1ZmY0Yjk5ZDE5NjY2NjQwMTZhZWI1NDI2YzM5OTE1NDIyMzRhN2VhOGY4MDI5OGEwYjhjYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GMoYGYRsXYzYnuyIQUQjCP9foWHZgkP1ReF5tKM-9Xw">
> @hkgnp

Can you try the latest release?

**Comment by yoghurtdewdew** [comment]
The latest seemed to work! Thanks for your great work!
