### ISSUE TITLE
[FR] insert schedule/deadline sentence in the second line of the block

### ISSUE THREAD

**Issue by e-zz** [hkgnp/logseq-datenlp-plugin#53]
Hi, the plugin is extremely helpful. But the `schedule/deadline: <date-time>` is not rendered properly in Logseq when not put in the second line of the block.

It would be perfect if the plugin allows to insert `schedule/deadline` in the correct line to make it render.

Thanks!

**Comment by hkgnp** [comment]
Oh sorry I don't understand. Do you have an example please?

**Comment by e-zz** [comment]
> Oh sorry I don't understand. Do you have an example please?

Yes, here is a minimal example. 
![deadline](https://github.com/hkgnp/logseq-datenlp-plugin/assets/37920155/cc322324-483a-496a-9327-e39df8b3951c)

DEADLINE/SCHEDULED has to be in the second line to be visible.

Hope this helps to clarify my request. Thanks!

**Comment by hkgnp** [comment]
Thanks for the clarification. The plugin simply replaces `%today` with the SCHEDULED reference. What is stopping you from putting in `%today` in line 1 to begin with since it is going to apply to the whole block?

**Comment by e-zz** [comment]
> Thanks for the clarification. The plugin simply replaces `%today` with the SCHEDULED reference. What is stopping you from putting in `%today` in line 1 to begin with since it is going to apply to the whole block?

Sorry I thought the plugin by default could parse dates no matter where they are. If that's not a designed behavior then I will close this FR. Thanks for the plugin again!
