### ISSUE TITLE
`scheduled` would appear continuously

### ISSUE THREAD

**Issue by yoghurtdewdew** [hkgnp/logseq-datenlp-plugin#54]
I found `scheduled` would appear continuously when using this plugin. 

![🗯️logseq-datenlp 出现scheduled](https://github.com/hkgnp/logseq-datenlp-plugin/assets/63794438/88472abf-2179-4234-bd25-c4ad28ac8666)

However, I have no date related words in that task. So I put the link I used in my task here.

` [1-s2.0-S1385894719305418-mmc1.docx](hook://file/aVU3m7GpQ?p=UERGLzI2NzQ5MzAxODM=&n=1%2Ds2%2E0%2DS1385894719305418%2Dmmc1%2Edocx)`

Will this be fixed?

Thanks for your great job! (*^▽^*)

**Comment by e-zz** [comment]
see  https://github.com/hkgnp/logseq-datenlp-plugin/issues/51

**Comment by yoghurtdewdew** [comment]
Thanks for solving my problem! I have edited the json file to change that character to $.
