### ISSUE TITLE
Semi parsing, won't parse

### ISSUE THREAD

**Issue by emms007** [hkgnp/logseq-datenlp-plugin#6]
Hello again Hkgnp,

I get blocks sent from telegram to my journal. They are written in the format "(HH:MM) text,  then I am back on my computer and I take care of scheduling the tasks. It seems that (HH:MM) prefix is breaking the semi auto paring.

For instance, the following is not parsed:
`(13:32) Followup email **done** pending @tomorrow`
=> Tomorrow is not parsed

**Comment by hkgnp** [comment]
Hi yes, the (HH:MM) is messing with the parsing. For now, please use the `/parse dates` function.
Will need some time to look into a solution!

**Comment by hkgnp** [comment]
@emms007, this is fixed in v3.3 in the marketplace.

**Comment by emms007** [comment]
This is fixed in general, but some example won't work for no reason;

Have you tried  those:
(11:30) try to do this @10December => works
(11:30) try to do this %10December => wont work

**Comment by hkgnp** [comment]
https://user-images.githubusercontent.com/47936793/152038889-5e62d529-8640-44f9-9c08-8ede44a74b96.mov

Seems to be working for me though? Do you have other examples to try?

**Comment by emms007** [comment]
Hi again.
In your screen recording you did  not put the timestamp like in my exemple.

`(11:30) try to do this @10December => works
(11:30) try to do this %10December => wont work`
See the output:
![image](https://user-images.githubusercontent.com/171033/152126324-55b09024-c9b3-4f71-8d60-807666d2a012.png)

**Comment by hkgnp** [comment]
> Hi again. In your screen recording you did not put the timestamp like in my exemple.
> 
> `(11:30) try to do this @10December `=> works `(11:30) try to do this %10December `=> wont work
> 
> See the output: ![image](https://user-images.githubusercontent.com/171033/152126324-55b09024-c9b3-4f71-8d60-807666d2a012.png)

Apologies. Please try again with v3.7 in the marketplace.

**Comment by emms007** [comment]
Awesome ;) ! thanks
