### ISSUE TITLE
Sidebar data processing

### ISSUE THREAD

**Issue by emms007** [hkgnp/logseq-datenlp-plugin#7]
Hello,
I am a bigfan of the plugin. I am migrating over my Todoist logic to this plugin.
I noticed another bug. If you open a page on side bar (shift click), the DateNlp events are not processed.
See example:
![image](https://user-images.githubusercontent.com/171033/152575652-c1a432a6-6d0c-41aa-96c7-77586305f468.png)

Doing the same in the main view works fine.
Hope this is just a simple fix for you.
Thanks !

**Comment by hkgnp** [comment]
@emms007 Hi! Yes, this is the current design! Have to find some time to implement the observer callback on the sidebar as well.

Inline date parsing is still quite "hackish" atm!

**Comment by hkgnp** [comment]
Fixed in 3.8.1
