### ISSUE TITLE
Additional languages?

### ISSUE THREAD

**Issue by georgd** [hkgnp/logseq-datenlp-plugin#9]
How are the languages implemented? Is it very difficult to add more? I’d like to use it in German.

If it’s necessary for adding the language to do some translation work, I’m ready to help.

**Comment by hkgnp** [comment]
You can try following the instructions [here](https://github.com/hkgnp/logseq-datenlp-plugin#changing-languages), and put "de". E.g. in your `logseq-datenlp-plugin.json` file:
{
    "lang": "de"
}

**Comment by georgd** [comment]
Sorry, that doesn't work. Perhaps the code in parseDates.tsx prevents it?

 ``` javascript
 ​    ​if​ ​(​lang​ ​===​ ​'fr'​ ​||​ ​lang​ ​===​ ​'ja'​ ​||​ ​lang​ ​===​ ​'nl'​ ​||​ ​lang​ ​===​ ​'en'​)​ ​{
```

**Comment by hkgnp** [comment]
Ah, apologies forgot to add in the partially supported languages.

Please update to v3.8.4 and try again.

**Comment by georgd** [comment]
Great, thanks! It works now. Could you please tell me in how far these languages are only partially supported?

**Comment by hkgnp** [comment]
I have actually no idea! I don't speak German so I can't test.
Perhaps maybe some linguistic styles within the German language are not
supported? I'm not sure.

**Comment by georgd** [comment]
OK, found out it’s [chrone-node](https://github.com/wanasit/chrono) where DE is missing some parts that are present in the fully supported ones. But the basic parsing is fine.

**Comment by hkgnp** [comment]
I see! Feel free to do PRs for chrono-node and it's merged, I'll update the dependency version on the plugin as well.

**Comment by natrius** [comment]
Is it possible to use english and german at the same time?
